name: AUTOONPUSH

#on : [push]

#controls when action will run
on:
  push:
    branches:
      - main
    paths:
      - 'dbscript/deploy/**'

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    environment:
      name: tesla
    steps:
    - uses: actions/checkout@v2
#note the below assums that a host path or volume is mounted into the container at /docker(or action wil dail)
    - name: Run 'Liquibase clearCheckSums' in Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args:  --url=jdbc:snowflake://skteukb-rq71849.snowflakecomputing.com/?db=tesla_db_github&schema=TESLA_SCHEMA&warehouse=chandramani --changeLogFile=/dbscript/mainChangelog.xml --username=${{secrets.SF_USERNAME}} --password=${{secrets.SF_PASSWORD}} --liquibase-schema-name=${{secrets.SF_SCHEMA}} --default-schema-name=${{secrets.SF_SCHEMA}} --log-level=debug clearCheckSums
        
    - name: Run 'Liquibase status' in Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=jdbc:snowflake://skteukb-rq71849.snowflakecomputing.com/?db=tesla_db_github&schema=TESLA_SCHEMA&warehouse=chandramani --changeLogFile=/dbscript/mainChangelog.xml --username=${{secrets.SF_USERNAME}} --password=${{secrets.SF_PASSWORD}} --liquibase-schema-name=${{secrets.SF_SCHEMA}} --default-schema-name=${{secrets.SF_SCHEMA}} --log-level=INFO status
        
    - name: Run 'Liquibase update' in Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=jdbc:snowflake://skteukb-rq71849.snowflakecomputing.com/?db=tesla_db_github&schema=TESLA_SCHEMA&warehouse=chandramani --changeLogFile=/dbscript/mainChangelog.xml --username=${{secrets.SF_USERNAME}} --password=${{secrets.SF_PASSWORD}} --liquibase-schema-name=${{secrets.SF_SCHEMA}} --default-schema-name=${{secrets.SF_SCHEMA}} --log-level=debug update
